version: '2'

services:

##### RECURSO-SOCIAL

  recurso_social:
    image: php_yii_ds
    volumes:
      - /var/www/html/desarrollo-social/recurso-social/backend-recurso-social:/var/www/html
    environment:
      DB_HOST: 'recurso_social_db'
      DB_NAME: 'recursosocial'
    labels:
     - "traefik.backend=recurso-social"
     - "traefik.frontend.rule=Host:recurso-social.local"
     - "traefik.port=80"

  recurso_social_db:
    image: mysql:5.6
    environment:
     MYSQL_ROOT_PASSWORD: root
    volumes:
     - /var/www/html/desarrollo-social/recurso-social/dbdata:/var/lib/mysql

##### PRIL

  pril:
    image: php_yii_ds
    volumes:
      - /var/www/html/desarrollo-social/pril/backend-pril:/var/www/html
    environment:
      DB_HOST: 'pril_db'
      DB_NAME: 'pril'
    labels:
     - "traefik.backend=pril"
     - "traefik.frontend.rule=Host:pril.local"
     - "traefik.port=80"

  pril_db:
    ports:
     - 3306:3306
    image: mysql:5.6
    environment:
     MYSQL_ROOT_PASSWORD: root
    volumes:
     - /var/www/html/desarrollo-social/pril/dbdata:/var/lib/mysql

##### REGISTRAL

  registral:
    image: php_yii_ds
    volumes:
      - /var/www/html/desarrollo-social/registral/desarrolloSocialREGISTRAL:/var/www/html
    environment:
      DB_HOST: 'registral_db'
      DB_NAME: 'registral'
    labels:
     - "traefik.backend=registral"
     - "traefik.frontend.rule=Host:registral.local"
     - "traefik.port=80"

  registral_db:
    image: mysql:5.6
    ports:
     - 3307:3306
    environment:
     MYSQL_ROOT_PASSWORD: root
    volumes:
     - /var/www/html/desarrollo-social/registral/dbdata:/var/lib/mysql

##### LUGAR

  lugar:
    image: php_yii_ds
    volumes:
      - /var/www/html/desarrollo-social/lugar/backend-lugar:/var/www/html
    environment:
      DB_HOST: 'lugar_db'
      DB_NAME: 'lugar'
    labels:
     - "traefik.backend=lugar"
     - "traefik.frontend.rule=Host:lugar.local"
     - "traefik.port=80"

  lugar_db:
    image: mysql:5.6
    environment:
     MYSQL_ROOT_PASSWORD: root
    volumes:
     - /var/www/html/desarrollo-social/lugar/dbdata:/var/lib/mysql

##### PROXY

  proxy:
    image: traefik:1.7.6
    restart: always
    command: --web --docker --docker.domain=local
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/proxy/traefik.toml:/etc/traefik/traefik.toml
    labels:
     - "traefik.backend=proxy"
     - "traefik.frontend.rule=Host:proxy.local"
     - "traefik.port=8080"

